# Generated by Django 6.0.7 on 2026-07-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Example: laptop, mobile, smart-watch', max_length=120, unique=True),
        ),
    ]
