# Generated by Django 6.0.7 on 2026-08-15 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصولات'},
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productspecification',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='brand',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کشور'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='نام آیکون از Lucide Icons', max_length=50, null=True, verbose_name='آیکون (Lucide)'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='ویژه'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='گارانتی'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ترتیب نمایش'),
        ),
    ]
