# Generated by Django 6.0.7 on 2026-08-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount_order_payment_method_and_more'),
        ('products', '0009_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='orders.order', verbose_name='سفارش مرتبط'),
        ),
    ]
