# Generated by Django 6.0.7 on 2026-08-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_review_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('hours', models.PositiveSmallIntegerField(default=12, verbose_name='ساعت')),
                ('minutes', models.PositiveSmallIntegerField(default=0, verbose_name='دقیقه')),
                ('seconds', models.PositiveSmallIntegerField(default=0, verbose_name='ثانیه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فروش ویژه',
                'verbose_name_plural': 'فروش\u200cهای ویژه',
            },
        ),
    ]
