# Generated by Django 6.0.7 on 2026-08-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='تخفیف'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('online', 'پرداخت آنلاین'), ('wallet', 'کیف پول'), ('cash', 'پرداخت در محل')], default='online', max_length=20, verbose_name='روش پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('standard', 'ارسال عادی'), ('express', 'ارسال فوری'), ('premium', 'ارسال ویژه')], default='standard', max_length=20, verbose_name='روش ارسال'),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='جمع کل (بدون تخفیف)'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='مالیات'),
        ),
    ]
