# Generated by Django 6.0.7 on 2026-08-20 13:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', 'شماره تلفن معتبر نیست')], verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید با 09 شروع شود و 11 رقم باشد', regex='^\\+?1?\\d{9,15}$')], verbose_name='شماره تلفن'),
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_created', 'سفارش جدید'), ('order_paid', 'پرداخت سفارش'), ('order_completed', 'تکمیل سفارش'), ('order_cancelled', 'لغو سفارش'), ('wishlist_added', 'افزودن به علاقه\u200cمندی'), ('wishlist_removed', 'حذف از علاقه\u200cمندی'), ('address_added', 'افزودن آدرس'), ('address_updated', 'ویرایش آدرس'), ('profile_updated', 'ویرایش پروفایل'), ('review_added', 'ثبت نظر'), ('login', 'ورود به حساب'), ('logout', 'خروج از حساب')], max_length=50, verbose_name='نوع فعالیت')),
                ('message', models.CharField(max_length=255, verbose_name='پیام فعالیت')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='داده\u200cهای اضافی')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'فعالیت کاربر',
                'verbose_name_plural': 'فعالیت\u200cهای کاربران',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='accounts_us_user_id_439e53_idx'), models.Index(fields=['type'], name='accounts_us_type_7979cf_idx')],
            },
        ),
    ]
