# Generated by Django 6.0.7 on 2026-08-18 14:37

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='کد تخفیف را با حروف بزرگ وارد کنید', max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=20, verbose_name='نوع تخفیف')),
                ('discount_value', models.PositiveIntegerField(help_text='مثلاً ۲۰ برای ۲۰٪ یا ۵۰۰۰۰ برای ۵۰,۰۰۰ تومان', verbose_name='مقدار تخفیف')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('min_order_amount', models.PositiveIntegerField(default=0, help_text='حداقل مبلغی که این کد قابل استفاده است', verbose_name='حداقل مبلغ سفارش')),
                ('max_discount_amount', models.PositiveIntegerField(blank=True, help_text='حداکثر مبلغ تخفیف (فقط برای درصدی)', null=True, verbose_name='حداکثر تخفیف')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='تعداد دفعاتی که این کد قابل استفاده است', null=True, verbose_name='تعداد استفاده مجاز')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='تعداد استفاده شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_public', models.BooleanField(default=False, help_text='آیا این کد برای همه کاربران قابل استفاده است؟', verbose_name='عمومی')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='شروع اعتبار')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='پایان اعتبار')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('used_by', models.ManyToManyField(blank=True, related_name='used_coupons', to=settings.AUTH_USER_MODEL, verbose_name='کاربران استفاده\u200cکننده')),
            ],
            options={
                'verbose_name': 'کد تخفیف',
                'verbose_name_plural': 'کدهای تخفیف',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='discounts_c_code_be8449_idx'), models.Index(fields=['valid_from', 'valid_to'], name='discounts_c_valid_f_ae6791_idx')],
            },
        ),
    ]
